# Generated by Django 4.1.5 on 2023-01-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('civilid', models.IntegerField()),
                ('phone_num', models.IntegerField()),
            ],
        ),
    ]
