# Generated by Django 4.1.5 on 2023-01-22 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='name_em',
        ),
    ]
