# Generated by Django 4.1.5 on 2023-01-22 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_rename_name_employee_name_em'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name_em',
            new_name='name',
        ),
    ]
